- name: Downloading Maven
  get_url:
      url: "https://dlcdn.apache.org/maven/maven-3/3.9.3/binaries/apache-maven-3.9.3-bin.tar.gz" 
      dest: /opt


- name: extract the tar file
  unarchive:
    src: /opt/apache-maven-3.9.3-bin.tar.gz
    dest: /opt
    remote_src: True
- name: Removing tart file
  file:
     path: /opt/apache-maven-3.9.3-bin.tar.gz
     state: absent
- name: Renaming a file
  command: mv /opt/apache-maven-3.9.3 /opt/maven
- name: set environment variable
  lineinfile: dest=/root/.bashrc line='export PATH=$PATH:/opt/maven/bin' insertafter='EOF' regexp='export PATH=\$PATH:/opt/maven/bin' state=present
- name: source the bashrc file
  shell: /root/.bashrc
  remote_user: ubuntu
 
