---
# Installing the Java (Open Jdk) 
- name: Install Java 1.8 
  apt: name=openjdk-8-jdk

# Adding the group tomcat
- name: add group "tomcat"
  group: name=tomcat

# Adding the user tomcat
- name: add user "tomcat"
  user: name=tomcat group=tomcat home=/usr/share/tomcat createhome=no
  become: True
  become_method: sudo

- name: Install acl
  apt: 
   state: latest
   update_cache: true
   pkg:
     - acl


- name: Create a Directory /opt/tomcat9
  become: yes
  file:
    path: /opt/tomcat9
    state: directory
    mode: 0755
    owner: tomcat
    group: tomcat


- name: Download Tomcat using unarchive
  become: yes
  unarchive:
    src: "https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.76/bin/apache-tomcat-9.0.76.tar.gz"
    dest: /opt/tomcat9
    mode: 0755
    remote_src: yes
    group: tomcat
    owner: tomcat

- name: Change ownership
  file:
    path: /opt/tomcat9
    owner: tomcat
    group: tomcat
    mode: "u+rwx,g+rx,o=rx"
    recurse: yes
    state: directory

- name: Copy Tomcat service from local to remote
  copy:
     src: templates/tomcat.service
     dest: /etc/systemd/system/tomcat.service
     mode: 0755    
#- name: Move files to the /opt/tomcat9 directory
 # become: true
  #become_user: tomcat
  #shell: "mv /opt/tomcat9/apache*/* /opt/tomcat9"
#- name: Copy file with owner and permissions
 # ansible.builtin.copy:
  #  src: /opt/tomcat9
   # dest: /opt/tomcat9
    #owner: tomcat
    #group: tomcat
    #mode: 0644   
- name: Reload the SystemD to re-read configurations
  become: yes
  systemd:
     daemon-reload: yes

- name: Enable the tomcat service and start
  become: yes
  systemd:
     name: tomcat
     enabled: yes
     state: started

- name: Connect to Tomcat server on port 8080 and check status 200 - Try 5 times
  tags: test
  uri:
    url: http://localhost:8080
  register: result
  until: "result.status == 200"
  retries: 5
  delay: 10

